### ISSUE TITLE
ED Screamer & Unit Platoons

### ISSUE THREAD

**Issue by InsideEarth2150** [InsideEarth2150/IEO-Updates#2]
Units that are in a platoon are not affected by the ED Screamer.

**Comment by Skeltek** [comment]
Should it be possible to fix platoon behavior, it should first be stated what the desired behavior should be.
I guess the platoon leader is not affected, while only forwarding orders to otherwise affected units. Several options how to fix.

**Comment by Animal-UK** [comment]
alpha fix developed by https://github.com/GvardianDLVII

https://www.youtube.com/watch?v=tZOxn0f-8V0&feature=youtu.be

**Comment by Animal-UK** [comment]
Replaced default platoon script with @Kumu222 platoon script that auto disbands upon creation.

**Comment by Kumu222** [comment]
How many in the community would be interested in restoring platoons in some fashion?

My proposed solution would again allow for the platoon with square and line formations but come at a cost to the player due to the exploits of the default platoon script.  

The exploit of being able to move "screamed" units would be subject to a time delay of perhaps 12-15 seconds after being given the MOVE order. Also the focused fire attack would be delayed by perhaps 5 sec.  The exploit of moving mixed fast and slow units would also be subject to an initial time delay. 

I believe this is a fair compromise for ED players who use screamers as well as for players who use platoons.

Note the delays can be negotiated by the community.

Let's hear what you think.

**Comment by koniecpolski** [comment]
What about pre-recorded orders?

**Comment by Kumu222** [comment]
I will check on that.

**Comment by Kumu222** [comment]
Any platoons given prerecorded orders and executed before the unit is screamed will continue their recorded orders....subject to the MOVE time delay for each move.
